### ISSUE TITLE
All of the findViewById calls should use listItemView (not convertView because that could be null)

### ISSUE THREAD

**Issue by kkuan2011** [udacity/beginner-android-custom-arrayadapter-example#10]
// Find the TextView in the list_item.xml layout with the ID version_name
        TextView nameTextView = (TextView) listItemView.findViewById(R.id.version_name);
        // Get the Version Name from the current AndroidFlavor object and set this text on the vNameTextView
        nameTextView.setText(currentAndroidFlavor.getVersionName());

        // Find the TextView in the list_item.xml layout with the ID version_number
        TextView numberTextView = (TextView) convertView.findViewById(R.id.version_number);
        // Get the Version Number from the current AndroidFlavor object and set this text on the vNumberTextView
        numberTextView.setText(currentAndroidFlavor.getVersionNumber());

        // Find the ImageView in the list_item.xml layout with the ID list_item_icon
        ImageView iconView = (ImageView) convertView.findViewById(R.id.list_item_icon);
        // Get the Image Resource ID from the current AndroidFlavor object and set the image to iconView
        iconView.setImageResource(currentAndroidFlavor.getImageResourceId());

**Comment by jlin27** [comment]
Updated in AndroidFlavorAdapter.java
